version: "3"
services:
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "5001:5001"

  shipping-service:
    build:
      context: ./shipping-service
    ports:
      - "5008:5008"
  
  users-service:
    build:
      context: ./users-service
    ports:
      - "5007:5007"

  billing-service:
    build:
      context: ./billing-service
    ports:
      - "5005:5005"
